# Generated by Django 4.0.1 on 2022-02-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_country_alter_address_options_publisher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
