# Generated by Django 4.0.2 on 2022-02-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_country_options_alter_publisher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
